# Generated by Django 4.2.7 on 2023-11-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('sheba_number', models.CharField(max_length=24, unique=True)),
                ('account_number', models.CharField(max_length=24, unique=True)),
                ('amount_limit', models.DecimalField(decimal_places=20, default=0, max_digits=32)),
                ('daily_amount_limit', models.DecimalField(decimal_places=20, default=0, max_digits=32)),
                ('company_daily_amount_limit', models.DecimalField(decimal_places=20, default=0, max_digits=32)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20)),
                ('sheba_number', models.CharField(max_length=24, unique=True)),
                ('card_number', models.CharField(max_length=24, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accept'), (2, 'Reject')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
