# Generated by Django 4.2.7 on 2023-11-23 10:05

from django.db import migrations, models
import django.utils.timezone
import otp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50)),
                ("expired_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=otp.models.captcha_image,
                    ),
                ),
            ],
        ),
    ]
