# Generated by Django 4.2.7 on 2023-11-12 12:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_unit', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_fee', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, choices=[('DONE', 'Done'), ('REQUESTED', 'Requested'), ('FAILED', 'Failed')], db_index=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('SELL', 'Sell'), ('BUY', 'Buy')], db_index=True, max_length=50, null=True)),
                ('order_create', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('ADMIN', 'Admin')], db_index=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_order', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
